import {Shop} from "../../types/data.ts";
import {Area, Unit} from "../../types/enums.ts";

export const equipShops: Shop[] = [
  {
    "name": "Elvin Garcia",
    "area": Area.ARCHI,
    "check-possible": false,
    "location": {x: 0.549651, y: 0.939678},
    "discounts": [0.0, 0.1, 0.15, 0.2],
    "furnitures": [
      {
        "name": "Small container",
        "price": 300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10, -1, -1, 30],
        "substance-storage": 750,
      },
      {
        "name": "Medium container",
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, -1, -1, 13],
        "substance-storage": 1500,
      },
      {
        "name": "Large container",
        "price": 900,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, -1, -1, 4],
        "substance-storage": 5000,
      },
      {
        "name": "Laboratory cabinet",
        "price": 5000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, -1, -1, 2],
        "slots": 8,
        "hideout-stash": 1,
      },
    ],
    "equipments": [
      {
        "name": "Laboratory tray",
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, -1, -1, 4],
        "tier": 1,
        "hideout-stash": 1,
        "substance-storage": 150,
        "visibility": 0.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Mortar",
        "price": 4000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, -1, -1, 3],
        "tier": 1,
        "visibility": 0.5,
        "crafting-speed": 0.4,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Drying Rack",
        "price": 7000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, -1, -1, 3],
        "tier": 1,
        "crafting-speed": 0.8,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Hybrid Dryer",
        "price": 46000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, -1, -1, 4],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1.3,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 50,
      },
      {
        "name": "Growbox",
        "price": 32000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, -1, -1, 3],
        "tier": 1,
        "visibility": 1.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 80,
      },
      {
        "name": "Rack (for plants)",
        "price": 34000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, -1, -1, 3],
        "tier": 2,
        "visibility": 1.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 150,
      },
      {
        "name": "Seedling box",
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 0, -1, 2],
        "tier": 2,
        "visibility": 0.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Kitchen stove with oven",
        "price": 20000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 0, -1, 2],
        "tier": 1,
        "visibility": 1,
        "crafting-speed": 0.7,
        "waste-amount": 1.2,
        "production-cost": 1,
        "energy-usage": 2500,
      },
      {
        "name": "Electric pressure cooker",
        "price": 11000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 0, -1, 2],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1.15,
        "waste-amount": 0.95,
        "production-cost": 1,
        "energy-usage": 2000,
      },
      {
        "name": "Small fermentation vat",
        "price": 11000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, -1, -1, 2],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Bucket",
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, -1, -1, 2],
        "tier": 1,
        "visibility": 0.5,
        "crafting-speed": 0.5,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
    ],
  },
  {
    "name": "Watto",
    "area": Area.ARCHI,
    "check-possible": true,
    "location": {x: 0.460391, y: 0.797539},
    "discounts": [0.0, 0.1],
    "furnitures": [
      {
        "name": "Shelf",
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
        "hideout-stash": 1,
        "substance-storage": 500,
      },
      {
        "name": "Chair",
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [6],
        "comfort": 1,
      },
      {
        "name": "Armchair",
        "price": 7000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
        "comfort": 2,
      },
      {
        "name": "Sofa",
        "price": 12000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
        "comfort": 3,
      },
      {
        "name": "Bed",
        "price": 8000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
        "comfort": 1,
      },
      {
        "name": "Double Bed",
        "price": 16000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "comfort": 2,
      },
      {
        "name": "Wardrobe (for clothes)",
        "price": 10000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "slots": 30,
        "hideout-stash": 1,
      },
      {
        "name": "Backpack Hanger",
        "price": 4000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": "Desk",
        "price": 5500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": "Table",
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
      },
      {
        "name": "Industrial Table",
        "price": 7000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": "Cabinet",
        "price": 4500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
        "slots": 10,
        "hideout-stash": 1,
      },
      {
        "name": "Metal Cabinet",
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
        "slots": 15,
      },
      {
        "name": "Dresser",
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
        "slots": 25,
        "hideout-stash": 2,
      },
      {
        "name": "Bookshelf",
        "price": 5000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
        "hideout-stash": 5,
        "substance-storage": 1500,
      },
      {
        "name": "Retro radio",
        "price": 11000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": "Pet bed",
        "price": 5000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": "Small safe",
        "price": 32000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
      },
      {
        "name": "Door lock",
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "security": 7,
      },
      {
        "name": "Ceiling Lamp",
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [6],
        "comfort": 1,
      },
      {
        "name": "Desk lamp",
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [6],
        "comfort": 1,
      },
      {
        "name": "Floor lamp",
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [6],
        "comfort": 1,
      },
      {
        "name": "Painting",
        "price": 4000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [6],
        "comfort": 1,
        "decoration": true,
      },
      {
        "name": "Potted plant",
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
        "comfort": 2,
        "decoration": true,
      },
      {
        "name": "Cactus sculpture (dot)",
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
        "comfort": 1,
        "decoration": true,
      },
      {
        "name": "Cactus sculpture (long)",
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
        "comfort": 1,
        "decoration": true,
      },
      {
        "name": "Cactus sculpture (long+dot)",
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
        "comfort": 1,
        "decoration": true,
      },
    ],
  },
  {
    "name": "Watto",
    "area": Area.SLAVS_BAY,
    "check-possible": false,
    "location": {x: 0.382802, y: 0.626392},
    "discounts": [0.0, 0.1, 0.15],
    "furnitures": [
      {
        "name": "Small barrel",
        "price": 1200,
        "amount": 2,
        "unit": Unit.ITEM,
        "quantity": [2, 3],
        "substance-storage": 10000,
      },
      {
        "name": "Medium barrel",
        "price": 2500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3],
        "substance-storage": 20000,
        "visibility": 0.5,
      },
      {
        "name": "Large barrel",
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3],
        "substance-storage": 50000,
        "visibility": 0.5,
      },
      {
        "name": "Small safe",
        "price": 35000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3, 3],
      },
      {
        "name": "Safe",
        "price": 250000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 1],
      },
      {
        "name": "Window bars",
        "price": 4500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 8],
        "visibility": 0.5,
        "security": 2,
      },
      {
        "name": "Window shutters",
        "price": 4200,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [4, 7],
        "visibility": -2,
        "security": 1,
        "blocks-grenades": true,
      },
      {
        "name": "Door lock",
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3, 5],
        "security": 7,
      },
      {
        "name": "Large door lock",
        "price": 8900,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3],
        "security": 15,
      },
    ],
    "equipments": [
      {
        "name": "Laboratory tray",
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 2],
        "tier": 1,
        "hideout-stash": 1,
        "substance-storage": 150,
        "visibility": 0.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Coffee grinder",
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 1],
        "tier": 2,
        "visibility": 0.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 120,
      },
      {
        "name": "Electric pressure cooker",
        "price": 32500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 2000,
      },
      {
        "name": "Laboratory autoclave",
        "price": 65000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1.25,
        "waste-amount": 0.8,
        "production-cost": 1,
        "energy-usage": 1400,
      },
      {
        "name": "Laboratory water bath",
        "price": 110000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 1],
        "tier": 3,
        "visibility": 1.5,
        "crafting-speed": 1.5,
        "waste-amount": 0.5,
        "production-cost": 1,
        "energy-usage": 2400,
      },
      {
        "name": "Laboratory ice bath",
        "price": 190000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 1],
        "tier": 4,
        "visibility": 2,
        "crafting-speed": 1.5,
        "waste-amount": 0.8,
        "production-cost": 1,
        "energy-usage": 1200,
      },
      {
        "name": "Laboratory centrifuge",
        "price": 140000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 1],
        "tier": 3,
        "visibility": 1,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 150,
      },
      {
        "name": "Laboratory oven",
        "price": 95000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 1],
        "tier": 3,
        "visibility": 1.5,
        "crafting-speed": 1.6,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 2000,
      },
      {
        "name": "Homemade soaking vat",
        "price": 12000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2],
        "tier": 2,
        "visibility": 2,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Growbox",
        "price": 33000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 3],
        "tier": 1,
        "visibility": 1.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 80,
      },
      {
        "name": "bucket",
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3],
        "tier": 1,
        "visibility": 0.5,
        "crafting-speed": 0.5,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
    ],
  },
  {
    "name": "Ghetto equipment store",
    "area": Area.SLAVS_BAY,
    "check-possible": false,
    "location": {x: 0.409066, y: 0.546062},
    "discounts": [0.0, 0.1],
    "furnitures": [
      {
        "name": "Small container",
        "price": 300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [15],
        "substance-storage": 750,
      },
      {
        "name": "Medium container",
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10],
        "substance-storage": 1500,
      },
      {
        "name": "Large container",
        "price": 900,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
        "substance-storage": 5000,
      },
      {
        "name": "Small barrel",
        "price": 1200,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
        "substance-storage": 10000,
      },
      {
        "name": "Medium barrel",
        "price": 2500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "substance-storage": 20000,
        "visibility": 0.5,
      },
    ],
    "equipments": [
      {
        "name": "Laboratory tray",
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
        "tier": 1,
        "visibility": 0.5,
        "hideout-stash": 1,
        "substance-storage": 150,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Kitchen stove with oven",
        "price": 25000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
        "tier": 1,
        "crafting-speed": 0.7,
        "waste-amount": 1.2,
        "production-cost": 1,
        "energy-usage": 2500,
      },
      {
        "name": "Electric pressure cooker",
        "price": 32500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 2000,
      },
      {
        "name": "Laboratory autoclave",
        "price": 65000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "tier": 2,
        "visibility": 2,
        "crafting-speed": 1.25,
        "waste-amount": 0.8,
        "production-cost": 1,
        "energy-usage": 1400,
      },
      {
        "name": "Laboratory water bath",
        "price": 110000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "tier": 3,
        "visibility": 1.5,
        "crafting-speed": 1.5,
        "waste-amount": 0.5,
        "production-cost": 1,
        "energy-usage": 2400,
      },
      {
        "name": "Laboratory centrifuge",
        "price": 140000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "tier": 3,
        "visibility": 1,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 150,
      },
      {
        "name": "Drying rack",
        "price": 11000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
        "tier": 1,
        "visibility": 1,
        "crafting-speed": 0.8,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Drying outdoor rack",
        "price": 23000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
        "tier": 2,
        "visibility": 3.5,
        "crafting-speed": 1.05,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Hybrid dryer",
        "price": 48000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1.3,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 50,
      },
      {
        "name": "Bucket",
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
        "tier": 1,
        "visibility": 0.5,
        "crafting-speed": 0.5,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Small fermentation vat",
        "price": 12000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "tier": 2,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Homemade soaking vat",
        "price": 42000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "tier": 2,
        "visibility": 2,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Growbox",
        "price": 33000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "tier": 1,
        "visibility": 1.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 80,
      },
      {
        "name": "Rack",
        "price": 35500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
        "tier": 2,
        "visibility": 1.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 150,
      },
      {
        "name": "Seedling box",
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "tier": 2,
        "visibility": 0.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
    ],
  },
]