import {Shop} from "../../types/data.ts";
import {Area, Item} from "../../types/enums.ts";

export const equipShops: Shop[] = [
  {
    "name": "Elvin Garcia",
    "area": Area.ARCHI,
    "check-possible": false,
    "location": {x: 0.549651, y: 0.939678},
    "discounts": [0.0, 0.1, 0.15, 0.2],
    "furnitures": [
      {
        "name": Item.SMALL_CONTAINER,
        "price": 300,
        "quantity": [10, -1, -1, 30],
      },
      {
        "name": Item.MEDIUM_CONTAINER,
        "price": 500,
        "quantity": [5, -1, -1, 13],
      },
      {
        "name": Item.LARGE_CONTAINER,
        "price": 900,
        "quantity": [2, -1, -1, 4],
      },
      {
        "name": Item.LABORATORY_CABINET,
        "price": 5000,
        "quantity": [1, -1, -1, 2],
      },
    ],
    "equipments": [
      {
        "name": Item.LABORATORY_TRAY,
        "price": 3000,
        "quantity": [2, -1, -1, 4],
      },
      {
        "name": Item.MORTAR,
        "price": 4000,
        "quantity": [1, -1, -1, 3],
      },
      {
        "name": Item.DRYING_RACK,
        "price": 7000,
        "quantity": [1, -1, -1, 3],
      },
      {
        "name": Item.HYBRID_DRYER,
        "price": 46000,
        "quantity": [2, -1, -1, 4],
      },
      {
        "name": Item.GROWBOX,
        "price": 32000,
        "quantity": [1, -1, -1, 3],
      },
      {
        "name": Item.RACK,
        "price": 34000,
        "quantity": [1, -1, -1, 3],
      },
      {
        "name": Item.SEEDLING_BOX,
        "price": 3000,
        "quantity": [0, 0, -1, 2],
      },
      {
        "name": Item.KITCHEN_STOVE,
        "price": 20000,
        "quantity": [0, 0, -1, 2],
      },
      {
        "name": Item.ELECTRIC_PRESSURE_COOKER,
        "price": 11000,
        "quantity": [0, 0, -1, 2],
      },
      {
        "name": Item.SMALL_FERMENTATION_VAT,
        "price": 11000,
        "quantity": [1, -1, -1, 2],
      },
      {
        "name": Item.BUCKET,
        "price": 2000,
        "quantity": [1, -1, -1, 2],
      },
    ],
  },
  {
    "name": "Watto",
    "area": Area.ARCHI,
    "check-possible": true,
    "location": {x: 0.460391, y: 0.797539},
    "discounts": [0.0, 0.1],
    "furnitures": [
      {
        "name": Item.SHELF,
        "price": 2000,
        "quantity": [5],
      },
      {
        "name": Item.CHAIR,
        "price": 3000,
        "quantity": [6],
      },
      {
        "name": Item.ARMCHAIR,
        "price": 7000,
        "quantity": [3],
      },
      {
        "name": Item.SOFA,
        "price": 12000,
        "quantity": [3],
      },
      {
        "name": Item.BED,
        "price": 8000,
        "quantity": [3],
      },
      {
        "name": Item.DOUBLE_BED,
        "price": 16000,
        "quantity": [1],
      },
      {
        "name": Item.WARDROBE,
        "price": 10000,
        "quantity": [1],
      },
      {
        "name": Item.BACKPACK_HANGER,
        "price": 4000,
        "quantity": [2],
      },
      {
        "name": Item.DESK,
        "price": 5500,
        "quantity": [2],
      },
      {
        "name": Item.TABLE,
        "price": 6000,
        "quantity": [3],
      },
      {
        "name": Item.INDUSTRIAL_TABLE,
        "price": 7000,
        "quantity": [2],
      },
      {
        "name": Item.CABINET,
        "price": 4500,
        "quantity": [3],
      },
      {
        "name": Item.METAL_CABINET,
        "price": 6000,
        "quantity": [2],
      },
      {
        "name": Item.DRESSER,
        "price": 9000,
        "quantity": [2],
      },
      {
        "name": Item.BOOKSHELF,
        "price": 5000,
        "quantity": [2],
      },
      {
        "name": Item.RETRO_RADIO,
        "price": 11000,
        "quantity": [2],
      },
      {
        "name": Item.PET_BED,
        "price": 5000,
        "quantity": [2],
      },
      {
        "name": Item.SMALL_SAFE,
        "price": 32000,
        "quantity": [3],
      },
      {
        "name": Item.DOOR_LOCK,
        "price": 6000,
        "quantity": [1],
      },
      {
        "name": Item.CEILING_LAMP,
        "price": 3000,
        "quantity": [6],
      },
      {
        "name": Item.DESK_LAMP,
        "price": 3000,
        "quantity": [6],
      },
      {
        "name": Item.FLOOR_LAMP,
        "price": 3000,
        "quantity": [6],
      },
      {
        "name": Item.PAINTING,
        "price": 4000,
        "quantity": [6],
      },
      {
        "name": Item.POTTED_PLANT,
        "price": 3000,
        "quantity": [5],
      },
      {
        "name": Item.CACTUS_SCULPTURE,
        "price": 2000,
        "quantity": [3],
      },
      {
        "name": Item.CACTUS_SCULPTURE,
        "price": 2000,
        "quantity": [3],
      },
      {
        "name": Item.CACTUS_SCULPTURE,
        "price": 2000,
        "quantity": [3],
      },
    ],
  },
  {
    "name": "Watto",
    "area": Area.SLAVS_BAY,
    "check-possible": false,
    "location": {x: 0.382802, y: 0.626392},
    "discounts": [0.0, 0.1, 0.15],
    "furnitures": [
      {
        "name": Item.SMALL_BARREL,
        "price": 1200,
        "quantity": [2, 3],
      },
      {
        "name": Item.MEDIUM_BARREL,
        "price": 2500,
        "quantity": [2, 3],
      },
      {
        "name": Item.LARGE_BARREL,
        "price": 6000,
        "quantity": [2, 3],
      },
      {
        "name": Item.SMALL_SAFE,
        "price": 35000,
        "quantity": [3, 3],
      },
      {
        "name": Item.SAFE,
        "price": 250000,
        "quantity": [1, 1],
      },
      {
        "name": Item.WINDOW_BARS,
        "price": 4500,
        "quantity": [5, 8],
      },
      {
        "name": Item.WINDOW_SHUTTERS,
        "price": 4200,
        "quantity": [4, 7],
      },
      {
        "name": Item.DOOR_LOCK,
        "price": 6000,
        "quantity": [3, 5],
      },
      {
        "name": Item.LARGE_DOOR_LOCK,
        "price": 8900,
        "quantity": [2, 3],
      },
    ],
    "equipments": [
      {
        "name": Item.LABORATORY_TRAY,
        "price": 3000,
        "quantity": [2, 2],
      },
      {
        "name": Item.COFFEE_GRINDER,
        "price": 9000,
        "quantity": [0, 1],
      },
      {
        "name": Item.ELECTRIC_PRESSURE_COOKER,
        "price": 32500,
        "quantity": [2, 3],
      },
      {
        "name": Item.LABORATORY_AUTOCLAVE,
        "price": 65000,
        "quantity": [1, 2],
      },
      {
        "name": Item.LABORATORY_WATER_BATH,
        "price": 110000,
        "quantity": [1, 1],
      },
      {
        "name": Item.LABORATORY_ICE_BATH,
        "price": 190000,
        "quantity": [0, 1],
      },
      {
        "name": Item.LABORATORY_CENTRIFUGE,
        "price": 140000,
        "quantity": [1, 1],
      },
      {
        "name": Item.LABORATORY_OVEN,
        "price": 95000,
        "quantity": [0, 1],
      },
      {
        "name": Item.HOMEMADE_SOAKING_VAT,
        "price": 12000,
        "quantity": [1, 2],
      },
      {
        "name": Item.GROWBOX,
        "price": 33000,
        "quantity": [1, 3],

      },
      {
        "name": Item.BUCKET,
        "price": 1000,
        "quantity": [2, 3],
      },
    ],
  },
  {
    "name": "Ghetto equipment store",
    "area": Area.SLAVS_BAY,
    "check-possible": false,
    "location": {x: 0.409066, y: 0.546062},
    "discounts": [0.0, 0.1],
    "furnitures": [
      {
        "name": Item.SMALL_CONTAINER,
        "price": 300,
        "quantity": [15],
      },
      {
        "name": Item.MEDIUM_CONTAINER,
        "price": 500,
        "quantity": [10],
      },
      {
        "name": Item.LARGE_CONTAINER,
        "price": 900,
        "quantity": [5],
      },
      {
        "name": Item.SMALL_BARREL,
        "price": 1200,
        "quantity": [2],
      },
      {
        "name": Item.MEDIUM_BARREL,
        "price": 2500,
        "quantity": [1],
      },
    ],
    "equipments": [
      {
        "name": Item.LABORATORY_TRAY,
        "price": 3000,
        "quantity": [2],
      },
      {
        "name": Item.KITCHEN_STOVE,
        "price": 25000,
        "quantity": [2],
      },
      {
        "name": Item.ELECTRIC_PRESSURE_COOKER,
        "price": 32500,
        "quantity": [1],
      },
      {
        "name": "Laboratory autoclave",
        "price": 65000,
        "amount": 1,
        "quantity": [1],
        "tier": 2,
        "visibility": 2,
        "crafting-speed": 1.25,
        "waste-amount": 0.8,
        "production-cost": 1,
        "energy-usage": 1400,
      },
      {
        "name": "Laboratory water bath",
        "price": 110000,
        "amount": 1,
        "quantity": [1],
        "tier": 3,
        "visibility": 1.5,
        "crafting-speed": 1.5,
        "waste-amount": 0.5,
        "production-cost": 1,
        "energy-usage": 2400,
      },
      {
        "name": "Laboratory centrifuge",
        "price": 140000,
        "amount": 1,
        "quantity": [1],
        "tier": 3,
        "visibility": 1,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 150,
      },
      {
        "name": "Drying rack",
        "price": 11000,
        "amount": 1,
        "quantity": [3],
        "tier": 1,
        "visibility": 1,
        "crafting-speed": 0.8,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Drying outdoor rack",
        "price": 23000,
        "amount": 1,
        "quantity": [2],
        "tier": 2,
        "visibility": 3.5,
        "crafting-speed": 1.05,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Hybrid dryer",
        "price": 48000,
        "amount": 1,
        "quantity": [2],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1.3,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 50,
      },
      {
        "name": "Bucket",
        "price": 1000,
        "amount": 1,
        "quantity": [2],
        "tier": 1,
        "visibility": 0.5,
        "crafting-speed": 0.5,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Small fermentation vat",
        "price": 12000,
        "amount": 1,
        "quantity": [1],
        "tier": 2,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Homemade soaking vat",
        "price": 42000,
        "amount": 1,
        "quantity": [1],
        "tier": 2,
        "visibility": 2,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Growbox",
        "price": 33000,
        "amount": 1,
        "quantity": [1],
        "tier": 1,
        "visibility": 1.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 80,
      },
      {
        "name": "Rack",
        "price": 35500,
        "amount": 1,
        "quantity": [2],
        "tier": 2,
        "visibility": 1.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 150,
      },
      {
        "name": "Seedling box",
        "price": 3000,
        "amount": 1,
        "quantity": [1],
        "tier": 2,
        "visibility": 0.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
    ],
  },
  {
    "name": "Ghetto equipment store",
    "area": Area.SANGRIENTA,
    "check-possible": false,
    "location": {x: 0.553256, y: 0.413876},
    "discounts": [0.0, 0.1, 0.15, 0.2],
    "furnitures": [
      {
        "name": "Small container",
        "price": 300,
        "amount": 1,
        "quantity": [-1, 20, 30],
        "substance-storage": 750,
      },
      {
        "name": "Medium container",
        "price": 500,
        "amount": 1,
        "quantity": [-1, 15, 20],
        "substance-storage": 1500,
      },
      {
        "name": "Large container",
        "price": 900,
        "amount": 1,
        "quantity": [-1, 8, 10],
        "substance-storage": 5000,
      },
      {
        "name": "Small barrel",
        "price": 2000,
        "amount": 1,
        "quantity": [2, 5, 8],
        "substance-storage": 10000,
      },
      {
        "name": "Medium barrel",
        "price": 3500,
        "amount": 1,
        "quantity": [1, 3, 5],
        "substance-storage": 20000,
        "visibility": 0.5,
      },
      {
        "name": "Large barrel",
        "price": 7000,
        "amount": 1,
        "quantity": [1, 2, 3],
        "substance-storage": 50000,
        "visibility": 0.5,
      },
      {
        "name": "Small safe",
        "price": 34000,
        "amount": 1,
        "quantity": [-1, 10, 15],
      },
      {
        "name": "Safe",
        "price": 240000,
        "amount": 1,
        "quantity": [-1, 8, 13],
      },
      {
        "name": "Large safe",
        "price": 600000,
        "amount": 1,
        "quantity": [-1, 2, 3],
      },
      {
        "name": "Window bars",
        "price": 4500,
        "amount": 1,
        "quantity": [-1, 8, 10],
        "visibility": 0.5,
        "security": 2,
      },
      {
        "name": "Window shutters",
        "price": 4000,
        "amount": 1,
        "quantity": [-1, 8, 10],
        "visibility": -2,
        "security": 1,
        "blocks-grenades": true,
      },
      {
        "name": "Door lock",
        "price": 6000,
        "amount": 1,
        "quantity": [-1, 7, 10],
        "security": 7,
      },
      {
        "name": "Large door lock",
        "price": 8500,
        "amount": 1,
        "quantity": [-1, 4, 5],
        "security": 15,
      },
      {
        "name": "Laboratory cabinet",
        "price": 5000,
        "amount": 1,
        "quantity": [-1, 4, 5],
        "slots": 8,
        "hideout-stash": 1,
      },
      {
        "name": "Large laboratory cabinet",
        "price": 19000,
        "amount": 1,
        "quantity": [-1, 3, 5],
        "slots": 40,
        "hideout-stash": 1,
      },
    ],
    "equipments": [
      {
        "name": "Laboratory tray",
        "price": 3000,
        "amount": 1,
        "quantity": [-1, 3, 4],
        "tier": 1,
        "visibility": 0.5,
        "hideout-stash": 1,
        "substance-storage": 150,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Mortar",
        "price": 4000,
        "amount": 1,
        "quantity": [-1, 4, 5],
        "tier": 1,
        "visibility": 0.5,
        "crafting-speed": 0.4,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Coffe grinder",
        "price": 8000,
        "amount": 1,
        "quantity": [-1, 3, 5],
        "tier": 2,
        "visibility": 0.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 120,
      },
      {
        "name": "Kitchen stove with oven",
        "price": 22000,
        "amount": 1,
        "quantity": [-1, 4, 5],
        "visibility": 1,
        "tier": 1,
        "crafting-speed": 0.7,
        "waste-amount": 1.2,
        "production-cost": 1,
        "energy-usage": 2500,
      },
      {
        "name": "Electric pressure cooker",
        "price": 30000,
        "amount": 1,
        "quantity": [-1, 3, 4],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1.15,
        "waste-amount": 0.95,
        "production-cost": 1,
        "energy-usage": 2000,
      },
      {
        "name": "Laboratory autoclave",
        "price": 65000,
        "amount": 1,
        "quantity": [-1, 3, 4],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1.3,
        "waste-amount": 0.8,
        "production-cost": 1,
        "energy-usage": 1400,
      },
      {
        "name": "Laboratory water bath",
        "price": 110000,
        "amount": 1,
        "quantity": [-1, 2, 3],
        "tier": 3,
        "visibility": 1.5,
        "crafting-speed": 1.6,
        "waste-amount": 0.5,
        "production-cost": 1,
        "energy-usage": 2400,
      },
      {
        "name": "Laboratory ice bath",
        "price": 190000,
        "amount": 1,
        "quantity": [0, 1, 1],
        "tier": 4,
        "visibility": 2,
        "crafting-speed": 1.7,
        "waste-amount": 0.5,
        "production-cost": 1,
        "energy-usage": 1200,
      },
      {
        "name": "Laboratory centrifuge",
        "price": 140000,
        "amount": 1,
        "quantity": [-1, 2, 3],
        "tier": 3,
        "visibility": 1,
        "crafting-speed": 1.7,
        "waste-amount": 0.4,
        "production-cost": 1,
        "energy-usage": 150,
      },
      {
        "name": "Laboratory orbital shaker",
        "price": 250000,
        "amount": 1,
        "quantity": [0, 1, 2],
        "tier": 4,
        "visibility": 1.5,
        "crafting-speed": 2,
        "waste-amount": 0.2,
        "production-cost": 1,
        "energy-usage": 300,
      },
      {
        "name": "Drying rack",
        "price": 7000,
        "amount": 1,
        "quantity": [-1, 5, 6],
        "tier": 1,
        "visibility": 1,
        "crafting-speed": 0.8,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Drying outdoor rack",
        "price": 21000,
        "amount": 1,
        "quantity": [-1, 5, 7],
        "tier": 2,
        "visibility": 3.5,
        "crafting-speed": 1.05,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Hybrid dryer",
        "price": 46000,
        "amount": 1,
        "quantity": [-1, 4, 5],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1.3,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 50,
      },
      {
        "name": "Laboratory oven",
        "price": 95000,
        "amount": 1,
        "quantity": [0, 1, 2],
        "tier": 3,
        "visibility": 1.5,
        "crafting-speed": 1.6,
        "waste-amount": 0.9,
        "production-cost": 1,
        "energy-usage": 2000,
      },
      {
        "name": "Large drying table",
        "price": 55000,
        "amount": 1,
        "quantity": [0, 0, 1],
        "tier": 2,
        "visibility": 2,
        "crafting-speed": 1.4,
        "waste-amount": 0.9,
        "production-cost": 1,
        "energy-usage": 4000,
      },
      {
        "name": "Bucket",
        "price": 2000,
        "amount": 1,
        "quantity": [-1, 3, 4],
        "tier": 1,
        "visibility": 0.5,
        "crafting-speed": 0.5,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Old barrel",
        "price": 4000,
        "amount": 1,
        "quantity": [-1, 2, 3],
        "tier": 1,
        "visibility": 1.5,
        "crafting-speed": 0.6,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Kitchen mixer",
        "price": 18000,
        "amount": 1,
        "quantity": [-1, 2, 3],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1.7,
        "waste-amount": 0.8,
        "production-cost": 1,
        "energy-usage": 1500,
      },
      {
        "name": "Small fermentation vat",
        "price": 11000,
        "amount": 1,
        "quantity": [-1, -1, 6],
        "visibility": 1,
        "tier": 2,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Homemade soaking vat",
        "price": 40000,
        "amount": 1,
        "quantity": [-1, 3, 4],
        "tier": 2,
        "visibility": 2,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Growbox",
        "price": 32000,
        "amount": 1,
        "quantity": [-1, 3, 5],
        "tier": 1,
        "visibility": 1.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 80,
      },
      {
        "name": "Rack (for plants)",
        "price": 35500,
        "amount": 1,
        "quantity": [-1, 4, 5],
        "tier": 2,
        "visibility": 1.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 150,
      },
      {
        "name": "Seedling box",
        "price": 3000,
        "amount": 1,
        "quantity": [-1, 5, 6],
        "tier": 2,
        "visibility": 0.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Outdoor pot box",
        "price": 15000,
        "amount": 1,
        "quantity": [-1, 3, 4],
        "tier": 2,
        "visibility": 2,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Plastic box (for plants)",
        "price": 4000,
        "amount": 1,
        "quantity": [-1, 2, 3],
        "tier": 2,
        "visibility": 0.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },

    ],
  },
]