import {Hideout} from "../../types/data.ts";
import {Area} from "../../types/enums.ts";

export const hideouts: Hideout[] = [
  // Small Island
  {
    "name": "Bunker",
    "area": Area.SMALL_ISLAND,
    "location": {x: 0.324095, y: 0.941388},
    "price": 0,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": false,
    "phoneline": false,
    "garden": false,
  },
  // Archipelago
  {
    "name": "Cottage",
    "area": Area.ARCHI,
    "location": {x: 0.567675, y: 0.962162},
    "price": 360000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "parking-spot": true,
  },
  {
    "name": "Cottage",
    "area": Area.ARCHI,
    "location": {x: 0.448032, y: 0.944473},
    "price": 230000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "garden": true,
    "parking-spot": true,
  },
  {
    "name": "House",
    "area": Area.ARCHI,
    "location": {x: 0.503991, y: 0.85865},
    "price": 400000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "parking-spot": true,
  },
  {
    "name": "House",
    "area": Area.ARCHI,
    "location": {x: 0.440135, y: 0.843888},
    "price": 190000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "garden": true,
    "parking-spot": true,
  },
  // Callejon
  {
    "name": "Cottage",
    "area": Area.CALLEJON,
    "location": {x: 0.513261, y: 0.793076},
    "price": 385000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "parking-spot": true,
    "garden": true,
  },
  {
    "name": "Apartment",
    "area": Area.CALLEJON,
    "location": {x: 0.530426, y: 0.700723},
    "price": 350000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "parking-spot": true,
  },
  {
    "name": "Cottage",
    "area": Area.CALLEJON,
    "location": {x: 0.494035, y: 0.709475},
    "price": 300000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "parking-spot": true,
  },
  {
    "name": "Barak",
    "area": Area.CALLEJON,
    "location": {x: 0.505193, y: 0.691973},
    "price": 250000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "parking-spot": true,
  },
  {
    "name": "Cottage",
    "area": Area.CALLEJON,
    "location": {x: 0.559092, y: 0.719605},
    "price": 390000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "phoneline": true,
  },
  // Farmers Island
  {
    "name": "House",
    "area": Area.FARMERS_ISLAND,
    "location": {x: 0.669464, y: 0.840969},
    "price": 610000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": false,
    "phoneline": false,
    "garden": true,
  },
  // Jungle
  {
    "name": "Apartment",
    "area": Area.JUNGLE,
    "location": {x: 0.543643, y: 0.637722},
    "price": 755000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "parking-spot": true,
  },
  {
    "name": "Cottage",
    "area": Area.JUNGLE,
    "location": {x: 0.528366, y: 0.650253},
    "price": 440000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "parking-spot": true,
  },
  {
    "name": "House",
    "area": Area.JUNGLE,
    "location": {x: 0.520298, y: 0.59515},
    "price": 870000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "phoneline": true,
    "garden": true,
    "parking-spot": true,
  },
  {
    "name": "Cottage",
    "area": Area.JUNGLE,
    "location": {x: 0.548621, y: 0.596008},
    "price": 460000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "phoneline": true,
    "garden": true,
    "parking-spot": true,
  },
  {
    "name": "Cottage",
    "area": Area.JUNGLE,
    "location": {x: 0.595998, y: 0.602188},
    "price": 520000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "garden": true,
  },
  // Slavs bay
  {
    "name": "House",
    "area": Area.SLAVS_BAY,
    "location": {x: 0.410954, y: 0.573868},
    "price": 820000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "parking-spot": true,
  },
  {
    "name": "Cottage",
    "area": Area.SLAVS_BAY,
    "location": {x: 0.470004, y: 0.576278},
    "price": 350000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "garden": true,
  },
  {
    "name": "Cottage",
    "area": Area.SLAVS_BAY,
    "location": {x: 0.432239, y: 0.594472},
    "price": 370000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "parking-spot": true,
  },
  {
    "name": "Apartment",
    "area": Area.SLAVS_BAY,
    "location": {x: 0.424858, y: 0.554474},
    "price": 485000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "parking-spot": true,
  },
  {
    "name": "House",
    "area": Area.SLAVS_BAY,
    "location": {x: 0.42503, y: 0.626583},
    "price": 650000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
  },
  // Peninsular
  {
    "name": "House",
    "area": Area.PENINSULAR,
    "location": {x: 0.283583, y: 0.553784},
    "price": 535000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "garden": true,
  },
  {
    "name": "Apartment",
    "area": Area.PENINSULAR,
    "location": {x: 0.261783, y: 0.62348},
    "price": 750000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "parking-spot": true,
  },
  {
    "name": "Apartment",
    "area": Area.PENINSULAR,
    "location": {x: 0.297659, y: 0.603898},
    "price": 620000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "garden": true,
    "parking-spot": true,
  },
  {
    "name": "House",
    "area": Area.PENINSULAR,
    "location": {x: 0.257491, y: 0.666732},
    "price": 480000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
  },
  {
    "name": "Warehouse",
    "area": Area.PENINSULAR,
    "location": {x: 0.325983, y: 0.636689},
    "price": 1150000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "parking-spot": true,
  },
  {
    "name": "Villa",
    "area": Area.PENINSULAR,
    "location": {x: 0.236205, y: 0.672398},
    "price": 4650000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "phoneline": true,
    "running-water": true,
    "garden": true,
    "parking-spot": true,
  },
  // Sangrienta
  {
    "name": "Villa",
    "area": Area.SANGRIENTA,
    "location": {x: 0.52768, y: 0.402031},
    "price": 6900000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "garden": true,
    "parking-spot": true,
  },
  {
    "name": "Shed",
    "area": Area.SANGRIENTA,
    "location": {x: 0.534031, y: 0.414906},
    "price": 400000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
  },
  {
    "name": "House",
    "area": Area.SANGRIENTA,
    "location": {x: 0.561324, y: 0.372486},
    "price": 1150000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "parking-spot": true,
  },
  {
    "name": "Apartment",
    "area": Area.SANGRIENTA,
    "location": {x: 0.525963, y: 0.360125},
    "price": 927500,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "garden": true,
    "parking-spot": true,
  },
  // Volcano Island
  // Dueno del mar
  {
    "name": "Cocaine Lab",
    "area": Area.DUENO_DEL_MAR,
    "location": {x: 0.445285, y: 0.445625},
    "price": 4000000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "garden": true,
  },
  {
    "name": "Cottage",
    "area": Area.DUENO_DEL_MAR,
    "location": {x: 0.479616, y: 0.33214},
    "price": 850000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "garden": true,
    "parking-spot": true,
    "is_apartment": true,
  },
  {
    "name": "Cottage",
    "area": Area.DUENO_DEL_MAR,
    "location": {x: 0.465712, y: 0.424851},
    "price": 210000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
  },
  {
    "name": "Garage",
    "area": Area.DUENO_DEL_MAR,
    "location": {x: 0.358083, y: 0.376798},
    "price": 380000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
  },
  {
    "name": "Storage Unit",
    "area": Area.DUENO_DEL_MAR,
    "location": {x: 0.327185, y: 0.383835},
    "price": 420000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
  },
  {
    "name": "House",
    "area": Area.DUENO_DEL_MAR,
    "location": {x: 0.393616, y: 0.394478},
    "price": 2_666_000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
    "is_apartment": true,
  },
  {
    "name": "Apartment",
    "area": Area.DUENO_DEL_MAR,
    "location": {x: 0.393101, y: 0.403919},
    "price": 1_525_000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "is_apartment": true,
    "running-water": true,
    "phoneline": true,
  },
  {
    "name": "Apartment",
    "area": Area.DUENO_DEL_MAR,
    "location": {x: 0.342634, y: 0.358086},
    "price": 4_200_000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "is_apartment": true,
    "running-water": true,
    "phoneline": true,
    "vault": true,
  },
  {
    "name": "Warehouse",
    "area": Area.DUENO_DEL_MAR,
    "location": {x: 0.425716, y: 0.348986},
    "price": 3_250_000,
    "visibility": 0,
    "security": 0,
    "comfort": 0,
    "running-water": true,
    "phoneline": true,
  },

  //
  // Bahia - Downtown
  // Bahia - Favela
]