import {Shop} from "../../types/data.ts";
import {Area, Item, Unit} from "../../types/enums.ts";

export const shops: Shop[] = [
  // Small Island
  {
    "name": "Shop",
    "area": Area.SMALL_ISLAND,
    "check-possible": false,
    "location": {
      "x": 0.334738,
      "y": 0.883381
    },
    "discounts": [0.0, 0.1, 0.2],
    "items": [
      {
        "name": Item.WATER_BOTTLE_SMALL,
        "price": 300,
        "amount": 500,
        "unit": Unit.LIQUID,
        "quantity": [10, 30]
      },
      {
        "name": Item.SAUSAGE,
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 10]
      },
      {
        "name": Item.BEER,
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 10]
      },
      {
        "name": Item.CIGARETTE_PACK,
        "price": 3750,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2]
      },
      {
        "name": Item.BUS_TICKET,
        "price": 20,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [15, 15]
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100, 300]
      },
      {
        "name": Item.PLASTIC_BAG,
        "price": 250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 5],
      }
    ]
  },
  {
    "name": "Marcus",
    "area": Area.SMALL_ISLAND,
    "check-possible": false,
    "location": {x: 0.323065, y: 0.944824},
    "discounts": [0.0, 0.1, 0.15, 0.2],
    "items": [
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [50, 100, 150],
      },
      {
        "name": Item.VIAL,
        "price": 2,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [30, 50, 80],
      },
      {
        "name": Item.ETHANOL,
        "price": 480,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [30, 50, 80],
      },
      {
        "name": Item.ACETONE,
        "price": 3000,
        "amount": 1000,
        "unit": Unit.LIQUID,
        "quantity": [0, 2, 3],
      },
      {
        "name": Item.AMP,
        "price": 12000,
        "amount": 10,
        "unit": Unit.MASS,
        "quantity": [3, 5, 6],
      },
      {
        "name": Item.PHENYL,
        "price": 2400,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [10, 12, 15],
      },
      {
        "name": Item.ACETIC_ACID,
        "price": 200,
        "amount": 100,
        "unit": Unit.LIQUID,
        "quantity": [10, 20, 30],
      },
      {
        "name": Item.AMP,
        "price": 61000,
        "amount": 50,
        "unit": Unit.MASS,
        "quantity": [0, 1, 1],
      },
      {
        "name": Item.BLANK_BLOTTER,
        "price": 425,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 0, 200],
      },
    ]
  },
  // Archipelago
  {
    "name": "General Store",
    "area": Area.ARCHI,
    "check-possible": false,
    "location": {
      "x": 0.477041,
      "y": 0.914439
    },
    "discounts": [0.0, 0.1, 0.2],
    "items": [
      {
        "name": Item.WATER_BOTTLE_SMALL,
        "price": 300,
        "amount": 500,
        "unit": Unit.LIQUID,
        "quantity": [8, 12]
      },
      {
        "name": Item.WATER_BOTTLE_MEDIUM,
        "price": -1,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [0, 1]
      },
      {
        "name": Item.SAUSAGE,
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [20, 30]
      },
      {
        "name": Item.CIGARETTE_PACK,
        "price": 3750,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2]
      },
      {
        "name": Item.BUS_TICKET,
        "price": 20,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [25]
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [500]
      },
      {
        "name": Item.PLASTIC_BAG,
        "price": 250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.CHOCOLATE_BAR,
        "price": 300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1]
      },
      {
        "name": Item.BACKPACK_SMALL,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1]
      },
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1]
      },
      {
        "name": Item.FERTILIZER,
        "price": 1750,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [5]
      },
      {
        "name": Item.CROWBAR,
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1]
      },
      {
        "name": Item.ETHANOL,
        "price": 480,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [10]
      },
      {
        "name": Item.VINEGAR,
        "price": 500,
        "amount": 500000,
        "unit": Unit.LIQUID,
        "quantity": [10]
      },
      {
        "name": Item.KEYCHAIN,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3]
      },
      {
        "name": Item.ROLLING_PAPERS,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [20]
      },
      {
        "name": Item.DUCT_TAPE,
        "price": 5,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100]
      },
      {
        "name": Item.STRETCH_FOIL,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [80]
      },
      {
        "name": Item.CASH_LARGE,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100000]
      }
    ]
  },
  {
    "name": "Botanist",
    "area": Area.ARCHI,
    "check-possible": false,
    "location": {"x": 0.550338, "y": 0.942071},
    "discounts": [0.0, 0.1, 0.15, 0.2],
    "items": [
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100, 200, 300, 400]
      },
      {
        "name": Item.FERTILIZER,
        "price": 1750,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [2, 2, 3, 3]
      },
      {
        "name": Item.ROLLING_PAPERS,
        "price": 8,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [40, 60, 80, 100]
      },
      {
        "name": Item.SEED_INDICA,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 7, 12, 15]
      },
      {
        "name": Item.WEED_INDICA,
        "price": 9000,
        "amount": 10,
        "unit": Unit.MASS,
        "quantity": [1, 2, 3, 4]
      },
      {
        "name": Item.UV_BULB_LARGE,
        "price": 9400,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 3, 3]
      },
      {
        "name": Item.HYDROPONIC_ELEMENTS,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 2, 3]
      },
      {
        "name": Item.FLOWER_POT,
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 2, 3]
      },
      {
        "name": Item.EMPTY_GLASS_PIPE,
        "price": 5,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10, 20, 30, 40]
      },
      {
        "name": Item.VIAL,
        "price": 2,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10, 20, 30, 40]
      },
      {
        "name": Item.LED_BULB_SMALL,
        "price": 3700,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 1, 1, 3]
      },
      {
        "name": Item.FAN,
        "price": 2250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 2, 3, 5]
      },
      {
        "name": Item.BLANK_BLOTTER,
        "price": 400,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 0, 0, 10]
      },
    ]
  },
  {
    "name": "Fuel depot",
    "area": Area.ARCHI,
    "check-possible": true,
    "location": {x: 0.520985, y: 0.879266},
    "discounts": [0.0],
    "items": [
      {
        "name": Item.BUS_TICKET,
        "price": 20,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 2,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.KEYCHAIN,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.GASOLINE,
        "price": 6000,
        "amount": 4000,
        "unit": Unit.LIQUID,
        "quantity": [8],
      },
      {
        "name": Item.GASOLINE,
        "price": 16500,
        "amount": 11000,
        "unit": Unit.LIQUID,
        "quantity": [2],
      },
      {
        "name": Item.METAL_PARTS,
        "price": 950,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.ELECTRIC_WIRES,
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [8],
      },
      {
        "name": Item.SIMPLE_MOTORBOAT,
        "price": 129000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.RIB_MOTORBOAT,
        "price": 165000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
    ]
  }, // Finished
  {
    "name": "Mechanic",
    "area": Area.ARCHI,
    "check-possible": true,
    "location": {x: 0.51635, y: 0.953064},
    "discounts": [0.0, 0.05, 0.1],
    "items": [
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2],
      },
      {
        "name": Item.CROWBAR,
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2],
      },
      {
        "name": Item.KEYCHAIN,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2],
      },
      {
        "name": Item.GASOLINE,
        "price": 6000,
        "amount": 4000,
        "unit": Unit.LIQUID,
        "quantity": [1, 1],
      },
      {
        "name": Item.GASOLINE,
        "price": 16500,
        "amount": 11000,
        "unit": Unit.LIQUID,
        "quantity": [0, 1],
      },
      {
        "name": Item.METAL_PARTS,
        "price": 950,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [8, 12],
      },
      {
        "name": Item.ELECTRIC_WIRES,
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [8, 12],
      },
    ]
  },
  // Callejon
  {
    "name": "Mini market",
    "area": Area.CALLEJON,
    "check-possible": true,
    "location": {x: 0.511544, y: 0.817107},
    "discounts": [0.0, 0.05, 0.1],
    "items": [
      {
        "name": Item.WATER_BOTTLE_SMALL,
        "price": 300,
        "amount": 500,
        "unit": Unit.LIQUID,
        "quantity": [10, 15, 20],
      },
      {
        "name": Item.BEER,
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10, 15, 20],
      },
      {
        "name": Item.CIGARETTE_PACK,
        "price": 3750,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [8, 12, 18],
      },
      {
        "name": Item.BUS_TICKET,
        "price": 20,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [50, 50, 50],
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [500, 1000, 1500],
      },
      {
        "name": Item.PLASTIC_BAG,
        "price": 250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10, 10, 10],
      },
      {
        "name": Item.CHOCOLATE_BAR,
        "price": 300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 10, 15],
      },
      {
        "name": Item.BACKPACK_SMALL,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3, 5, 7],
      },
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 4, 6],
      },
      {
        "name": Item.FERTILIZER,
        "price": 1200,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [3, 6, 9],
      },
      {
        "name": Item.CROWBAR,
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 3],
      },
      {
        "name": Item.ETHANOL,
        "price": 480,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [0, 20, 30],
      },
      {
        "name": Item.VINEGAR,
        "price": 500,
        "amount": 500000,
        "unit": Unit.LIQUID,
        "quantity": [10, 20, 30],
      },
      {
        "name": Item.KEYCHAIN,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3, 4, 5],
      },
      {
        "name": Item.ROLLING_PAPERS,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [40, 60, 80],
      },
      {
        "name": Item.DUCT_TAPE,
        "price": 5,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100, 500, 1000],
      },
      {
        "name": Item.STRETCH_FOIL,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [80, 450, 950],
      },
      {
        "name": Item.CASH_LARGE,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100000, 200000, 300000],
      },
      {
        "name": Item.EMPTY_GLASS_PIPE,
        "price": 4,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10, 20, 30],
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [50, 100, 150],
      },
      {
        "name": Item.WATER_BOTTLE_MEDIUM,
        "price": 1300,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [5, 10, 15],
      },
      {
        "name": Item.PACKET_SUGAR,
        "price": 1200,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [10, 15, 20],
      },
      {
        "name": Item.PACKET_FLOUR,
        "price": 550,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [10, 15, 20],
      },
      {
        "name": Item.PACKET_SALT,
        "price": 450,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [10, 15, 20],
      },
      {
        "name": Item.POPPY_SEED_PACK,
        "price": 3200,
        "amount": 100,
        "unit": Unit.MASS,
        "quantity": [2, 4, 6],
      },
      {
        "name": Item.CACAO_POWDER,
        "price": 1500,
        "amount": 500,
        "unit": Unit.MASS,
        "quantity": [8, 12, 18],
      },
      {
        "name": Item.ETHANOL,
        "price": 480,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [10, 20, 30],
      },
      {
        "name": Item.TABACCO_PACK,
        "price": 4500,
        "amount": 50,
        "unit": Unit.MASS,
        "quantity": [3, 4, 7],
      },
      {
        "name": Item.ACETONE,
        "price": 3000,
        "amount": 1000,
        "unit": Unit.LIQUID,
        "quantity": [1, 3, 5],
      },
      {
        "name": Item.FERTILIZER,
        "price": 8750,
        "amount": 5000,
        "unit": Unit.MASS,
        "quantity": [2, 3, 4],
      },
      {
        "name": Item.FERTILIZER_SYNTHETIC,
        "price": 1200,
        "amount": 3000,
        "unit": Unit.MASS,
        "quantity": [3, 5, 9],
      },
      {
        "name": Item.COOKING_POT,
        "price": 2500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3, 4, 5],
      },
      {
        "name": Item.FLASHLIGHT,
        "price": 4500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 1, 2],
      },
      {
        "name": Item.WIRE_CUTTERS,
        "price": 3500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 2, 3],
      },
      {
        "name": Item.MAP,
        "price": 2300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 4, 6],
      },
      {
        "name": Item.BANDAGE,
        "price": 8000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3, 5, 7],
      },
      {
        "name": Item.MOBILE_PHONE,
        "price": 19000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 1, 2],
      },
    ]
  }, // Finished
  {
    "name": "Fuel depot",
    "area": Area.CALLEJON,
    "check-possible": true,
    "location": {x: 0.52562, y: 0.737114},
    "discounts": [0.0],
    "items": [
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.CROWBAR,
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.GASOLINE,
        "price": 6000,
        "amount": 4000,
        "unit": Unit.LIQUID,
        "quantity": [10],
      },
      {
        "name": Item.GASOLINE,
        "price": 16500,
        "amount": 11000,
        "unit": Unit.LIQUID,
        "quantity": [3],
      },
      {
        "name": Item.METAL_PARTS,
        "price": 900,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10],
      },
      {
        "name": Item.ELECTRIC_WIRES,
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [8],
      },
      {
        "name": Item.WIRE_CUTTERS,
        "price": 4500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.MAP,
        "price": 2500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
    ]
  }, // Finished
  {
    "name": "Hardware store",
    "area": Area.CALLEJON,
    "check-possible": false,
    "location": {x: 0.531799, y: 0.698493},
    "discounts": [0.0, 0.1, 0.2],
    "items": [
      {
        "name": Item.GLASSES,
        "price": 1100,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3, 5],
      },
      {
        "name": Item.BEANIE,
        "price": 400,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 4, 6],
      },
      {
        "name": Item.BASEBALL_CAP,
        "price": 300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3, 4, 5],
      },
      {
        "name": Item.TSHIRT,
        "price": 450,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3, 5],
      },
      {
        "name": Item.PANTS,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3, 5],
      },
      {
        "name": Item.SPORT_PANTS,
        "price": 1700,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 1, 2],
      },
      {
        "name": Item.SWEATSHIRT,
        "price": 1850,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 1, 2],
      },
      {
        "name": Item.SNEAKERS,
        "price": 2250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 2],
      },
      {
        "name": Item.FANNYPACK,
        "price": 1100,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 2, 3],
      },
      {
        "name": Item.BALACLAVA,
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 2],
      },
      {
        "name": Item.BUS_TICKET,
        "price": 20,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [25, 25, 25],
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [500, 1000, 1500],
      },
      {
        "name": Item.PLASTIC_BAG,
        "price": 250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 5, 5],
      },
      {
        "name": Item.BACKPACK_SMALL,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 2, 3],
      },
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3, 3],
      },
      {
        "name": Item.DUCT_TAPE,
        "price": 5,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100, 500, 1000],
      },
      {
        "name": Item.STRETCH_FOIL,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [80, 450, 950],
      },
      {
        "name": Item.CASH_LARGE,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100000, 200000, 300000],
      },
      {
        "name": Item.VIAL,
        "price": 2,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 100, 150],
      },
      {
        "name": Item.METAL_PARTS,
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [8, 12, 18],
      },
      {
        "name": Item.ELECTRIC_WIRES,
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [8, 12, 18],
      },
      {
        "name": Item.FLASHLIGHT,
        "price": 4000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 2, 3],
      },
      {
        "name": Item.WIRE_CUTTERS,
        "price": 4500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 3],
      },
      {
        "name": Item.MAP,
        "price": 2300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 1, 2],
      },
      {
        "name": Item.BANDAGE,
        "price": 8000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3, 4],
      },
      {
        "name": Item.MOBILE_PHONE,
        "price": 19000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 2],
      },
      {
        "name": Item.FIRECRACKER,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3, 5, 9],
      },
      {
        "name": Item.BACKPACK_MEDIUM,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 1, 2],
      },
      {
        "name": Item.KEYCHAIN,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 4, 5],
      },
      {
        "name": Item.FLASHLIGHT_HID,
        "price": 5400,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 1, 2],
      },
      {
        "name": Item.HAMMER,
        "price": 10000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 2, 3],
      },
      {
        "name": Item.CROWBAR,
        "price": 11000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 2, 3],
      },
      {
        "name": Item.SHOVEL,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 2, 3],
      },
      {
        "name": Item.BOLT_CUTTER,
        "price": 8000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 1, 2],
      },
      {
        "name": Item.KNIFE,
        "price": 15000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 1, 2],
      },
      {
        "name": Item.UV_BULB_LARGE,
        "price": 6400,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 2, 3],
      },
      {
        "name": Item.HYDROPONIC_ELEMENTS,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 2, 3],
      },
      {
        "name": Item.FLOWER_POT,
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 3, 4],
      },
    ]
  }, // Finished
  {
    "name": "General Store",
    "area": Area.CALLEJON,
    "check-possible": false,
    "location": {x: 0.515492, y: 0.69317},
    "discounts": [0.0, 0.1, 0.2],
    "items": [
      {
        "name": Item.WATER_BOTTLE_SMALL,
        "price": 300,
        "amount": 500,
        "unit": Unit.LIQUID,
        "quantity": [10, 15, 20],
      },
      {
        "name": Item.WATER_BOTTLE_MEDIUM,
        "price": 1300,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [3, 4, 5],
      },
      {
        "name": Item.BEER,
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [6, 10, 15],
      },
      {
        "name": Item.PACKET_SODA,
        "price": 700,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [10, 15, 20],
      },
      {
        "name": Item.FERTILIZER,
        "price": 1750,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [5, 8, 12],
      },
      {
        "name": Item.FERTILIZER,
        "price": 8700,
        "amount": 5000,
        "unit": Unit.MASS,
        "quantity": [0, 2, 3],
      },
      {
        "name": Item.CIGARETTE_PACK,
        "price": 3750,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [4, 6, 8],
      },
      {
        "name": Item.TABACCO_PACK,
        "price": 4500,
        "amount": 50,
        "unit": Unit.MASS,
        "quantity": [2, 3, 5],
      },
      {
        "name": Item.ACETONE,
        "price": 3000,
        "amount": 1000,
        "unit": Unit.LIQUID,
        "quantity": [5, 8, 12],
      },
      {
        "name": Item.ACETONE,
        "price": 14000,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [0, 2, 3],
      },
      {
        "name": Item.ETHANOL,
        "price": 480,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [10, 20, 30],
      },
      {
        "name": Item.KEYCHAIN,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 3],
      },
      {
        "name": Item.COOKING_POT,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3, 5, 8],
      },
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 4, 6],
      },
      {
        "name": Item.GASOLINE,
        "price": 6000,
        "amount": 4000,
        "unit": Unit.LIQUID,
        "quantity": [2, 3, 4],
      },
      {
        "name": Item.BANDAGE,
        "price": 8000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 3],
      },
      {
        "name": Item.MAP,
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 4, 6],
      },
      {
        "name": Item.BUS_TICKET,
        "price": 20,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100, 100, 100],
      },
      {
        "name": Item.BLANK_BLOTTER,
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 10, 30],
      },
      {
        "name": Item.ROLLING_PAPERS,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [140, 160, 180],
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1000, 3000, 5000],
      },
      {
        "name": Item.DUCT_TAPE,
        "price": 5,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100, 500, 1000],
      },
      {
        "name": Item.STRETCH_FOIL,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [80, 450, 950],
      },
      {
        "name": Item.PLASTIC_BAG,
        "price": 250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 5, 5],
      },
      {
        "name": Item.CASH_LARGE,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100000, 200000, 300000],
      },
      {
        "name": Item.FESTIVE_SPICE_PACK,
        "price": 550,
        "amount": 600,
        "unit": Unit.MASS,
        "quantity": [-1, 15, 20],
      },
    ]
  },
  // Farmers island
  {
    "name": "Farm Shop",
    "area": Area.FARMERS_ISLAND,
    "check-possible": false,
    "location": {x: 0.64715, y: 0.810239},
    "discounts": [0.0, 0.1],
    "items": [
      {
        "name": Item.UV_BULB_LARGE,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.HYDROPONIC_ELEMENTS,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.FLOWER_POT,
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.PACKET_FLOUR,
        "price": 550,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [50],
      },
      {
        "name": Item.FERTILIZER,
        "price": 8500,
        "amount": 5000,
        "unit": Unit.MASS,
        "quantity": [5],
      },
      {
        "name": Item.FERTILIZER_SYNTHETIC,
        "price": 1200,
        "amount": 3000,
        "unit": Unit.MASS,
        "quantity": [3],
      },
      {
        "name": Item.ERGOT_RYE,
        "price": 1600,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [50],
      },
      {
        "name": Item.SHOVEL,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.PITCHFORK,
        "price": 10000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
    ]
  },
  {
    "name": "Poppy store",
    "area": Area.FARMERS_ISLAND,
    "check-possible": false,
    "location": {x: 0.646806, y: 0.846119},
    "discounts": [0.0, 0.1, 0.2],
    "items": [
      {
        "name": Item.POPPY_HEAD_YOUNG,
        "price": 550,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100, 200, 300],
      },
      {
        "name": Item.POPPY_SEED_PACK,
        "price": 3200,
        "amount": 100,
        "unit": Unit.MASS,
        "quantity": [30, 50, 70],
      },
      {
        "name": Item.POPPY_SEED_PACK,
        "price": 31000,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [2, 4, 6],
      },
      {
        "name": Item.FERTILIZER,
        "price": 8500,
        "amount": 5000,
        "unit": Unit.MASS,
        "quantity": [5, 8, 13],
      },
      {
        "name": Item.FERTILIZER_SYNTHETIC,
        "price": 1200,
        "amount": 3000,
        "unit": Unit.MASS,
        "quantity": [3, 5, 9],
      },
      {
        "name": Item.UV_BULB_LARGE,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 8, 10],
      },
      {
        "name": Item.FLOWER_POT,
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 10, 15],
      },
      {
        "name": Item.HYDROPONIC_ELEMENTS,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 3],
      },
      {
        "name": Item.SHOVEL,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 3],
      },
      {
        "name": Item.PITCHFORK,
        "price": 10000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 3],
      },
    ]
  }, // Finished
  // Jungle
  {
    "name": "Hardware store",
    "area": Area.JUNGLE,
    "check-possible": false,
    "location": {x: 0.582094, y: 0.637036},
    "discounts": [0.0, 0.1],
    "items": [
      {
        "name": Item.COOKING_POT,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.HAMMER,
        "price": 10000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.CROWBAR,
        "price": 11000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.WRENCH,
        "price": 14000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.SHOVEL,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.MULTITOOL,
        "price": 5300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.WIRE_CUTTERS,
        "price": 4500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.BOLT_CUTTER,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.KNIFE,
        "price": 15000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.KEYCHAIN,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
      },
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.FLASHLIGHT,
        "price": 4000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.FLASHLIGHT_HID,
        "price": 5400,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.FIELD_BOOTS,
        "price": 8900,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.FANNYPACK,
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
      },
      {
        "name": Item.BACKPACK_MEDIUM,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.ACETONE,
        "price": 7200,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [1],
      },
      {
        "name": Item.AMMONIA,
        "price": 6000,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [1],
      },
      {
        "name": Item.METHANOL,
        "price": 1150,
        "amount": 300,
        "unit": Unit.LIQUID,
        "quantity": [1],
      },
      {
        "name": Item.METHANOL,
        "price": 1150,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [1],
      },
      {
        "name": Item.LED_BULB_SMALL,
        "price": 1650,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [4],
      },
      {
        "name": "Led bulb large",
        "price": 3900,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
      },
      {
        "name": Item.UV_BULB_LARGE,
        "price": 9400,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.HYDROPONIC_ELEMENTS,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [4],
      },
      {
        "name": Item.FLOWER_POT,
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.FAN,
        "price": 2250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": "Disarming card",
        "price": 35000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.FIRECRACKER,
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10],
      },
      {
        "name": Item.METAL_PARTS,
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10],
      },
      {
        "name": Item.ELECTRIC_WIRES,
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10],
      },
      {
        "name": "Combat ration",
        "price": 13000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10],
      },
      {
        "name": Item.VIAL,
        "price": 2,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [50],
      },
      {
        "name": Item.ROLLING_PAPERS,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [20],
      },
      {
        "name": Item.DUCT_TAPE,
        "price": 5,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100],
      },
      {
        "name": Item.STRETCH_FOIL,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [80],
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [500],
      },
      {
        "name": Item.BUS_TICKET,
        "price": 20,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [25],
      },
      {
        "name": Item.PLASTIC_BAG,
        "price": 250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.CASH_LARGE,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100000],
      },
    ],
  },
  {
    "name": "Moonshiner",
    "area": Area.JUNGLE,
    "check-possible": false,
    "location": {x: 0.533344, y: 0.6414999},
    "discounts": [0.0, 0.1],
    "items": [
      {
        "name": Item.ETHANOL,
        "price": 450,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [100],
      },
      {
        "name": Item.ACETIC_ACID,
        "price": 200,
        "amount": 100,
        "unit": Unit.LIQUID,
        "quantity": [50],
      },
      {
        "name": Item.ACETONE,
        "price": 12000,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [1],
      },
    ]
  },
  {
    "name": "Meth store",
    "area": Area.JUNGLE,
    "check-possible": false,
    "location": {x: 0.600117, y: 0.64785},
    "discounts": [0.0, 0.05, 0.1],
    "items": [
      {
        "name": Item.METH,
        "price": 18000,
        "amount": 10,
        "unit": Unit.MASS,
        "quantity": [1, 2],
      },
      {
        "name": Item.EPHEDRINE,
        "price": 13500,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [5],
      },
      {
        "name": Item.LODORIC_ACID,
        "price": 450,
        "amount": 100,
        "unit": Unit.LIQUID,
        "quantity": [10],
      },
      {
        "name": Item.ETHANOL,
        "price": 480,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [10],
      }, {
        "name": Item.BLANK_BLOTTER,
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10],
      },
      {
        "name": Item.VIAL,
        "price": 2,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [50],
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [50],
      },
    ]
  },
  {
    "name": "General store",
    "area": Area.JUNGLE,
    "check-possible": false,
    "location": {x: 0.514119, y: 0.599957},
    "discounts": [0.0, 0.1],
    "items": [
      {
        "name": Item.WATER_BOTTLE_SMALL,
        "price": 300,
        "amount": 500,
        "unit": Unit.LIQUID,
        "quantity": [10],
      },
      {
        "name": Item.WATER_BOTTLE_MEDIUM,
        "price": 1300,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [1],
      },
      {
        "name": Item.BEER,
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [6],
      },
      {
        "name": Item.PACKET_FLOUR,
        "price": 550,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [10],
      },
      {
        "name": Item.PACKET_SALT,
        "price": 450,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [10],
      },
      {
        "name": Item.PACKET_SODA,
        "price": 700,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [5],
      },
      {
        "name": Item.VINEGAR,
        "price": 500,
        "amount": 500000,
        "unit": Unit.LIQUID,
        "quantity": [10],
      },
      {
        "name": Item.CACAO_POWDER,
        "price": 1250,
        "amount": 500,
        "unit": Unit.MASS,
        "quantity": [2],
      },
      {
        "name": Item.POPPY_SEED_PACK,
        "price": 3200,
        "amount": 100,
        "unit": Unit.MASS,
        "quantity": [2],
      },
      {
        "name": Item.CHOCOLATE_BAR,
        "price": 300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.CIGARETTE_PACK,
        "price": 3750,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.ANTIVENOM,
        "price": 10000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.ETHANOL,
        "price": 480,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [10],
      },
      {
        "name": Item.ACETONE,
        "price": 3000,
        "amount": 1000,
        "unit": Unit.LIQUID,
        "quantity": [1],
      },
      {
        "name": Item.AMMONIA,
        "price": 1750,
        "amount": 1000,
        "unit": Unit.LIQUID,
        "quantity": [3],
      },
      {
        "name": Item.FERTILIZER,
        "price": 1750,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [3],
      },
      {
        "name": Item.GASOLINE,
        "price": 6000,
        "amount": 4000,
        "unit": Unit.LIQUID,
        "quantity": [2],
      },
      {
        "name": Item.KEYCHAIN,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.BANDAGE,
        "price": 8000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
      },
      {
        "name": Item.MAP,
        "price": 2300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.BUS_TICKET,
        "price": 20,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [25],
      },
      {
        "name": Item.ROLLING_PAPERS,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [20],
      },
      {
        "name": Item.DUCT_TAPE,
        "price": 5,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100],
      },
      {
        "name": Item.STRETCH_FOIL,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [80],
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [500],
      },
      {
        "name": Item.PLASTIC_BAG,
        "price": 250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.CASH_LARGE,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100000],
      },
    ]
  },
  {
    "name": "Senor Teo",
    "area": Area.JUNGLE,
    "check-possible": false,
    "location": {x: 0.588617, y: 0.608196},
    "discounts": [0.0, 0.1],
    "items": [
      {
        "name": Item.MAP,
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
    ]
  },
  // Slavs bay
  {
    "name": "Bogdan the mechanic",
    "area": Area.SLAVS_BAY,
    "check-possible": true,
    "location": {x: 0.327528, y: 0.628621},
    "discounts": [0.0, 0.05],
    "items": [
      {
        "name": Item.METAL_PARTS,
        "price": 950,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [15],
      },
      {
        "name": Item.ELECTRIC_WIRES,
        "price": 1000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [15],
      },
      {
        "name": Item.GASOLINE,
        "price": 6000,
        "amount": 4000,
        "unit": Unit.LIQUID,
        "quantity": [1],
      },
      {
        "name": Item.GASOLINE,
        "price": 16500,
        "amount": 11000,
        "unit": Unit.LIQUID,
        "quantity": [1],
      },
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.FLASHLIGHT,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.CROWBAR,
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.KEYCHAIN,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.CAR,
        "price": 300000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
    ]
  },
  {
    "name": "General store",
    "area": Area.SLAVS_BAY,
    "check-possible": false,
    "location": {x: 0.327356, y: 0.619695},
    "discounts": [0.0, 0.1],
    "items": [
      {
        "name": Item.WATER_BOTTLE_SMALL,
        "price": 300,
        "amount": 500,
        "unit": Unit.LIQUID,
        "quantity": [10],
      },
      {
        "name": Item.WATER_BOTTLE_MEDIUM,
        "price": 2300,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [1],
      },
      {
        "name": Item.CIGARETTE_PACK,
        "price": 3750,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [6],
      },
      {
        "name": Item.TABACCO_PACK,
        "price": 4500,
        "amount": 50,
        "unit": Unit.MASS,
        "quantity": [1],
      },
      {
        "name": Item.CHOCOLATE_BAR,
        "price": 300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.CACAO_POWDER,
        "price": 1250,
        "amount": 500,
        "unit": Unit.MASS,
        "quantity": [2],
      },
      {
        "name": Item.PACKET_SUGAR,
        "price": 1200,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [2],
      },
      {
        "name": Item.PACKET_FLOUR,
        "price": 550,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [10],
      },
      {
        "name": Item.PACKET_SALT,
        "price": 450,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [5],
      },
      {
        "name": Item.PACKET_SODA,
        "price": 700,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [10],
      },
      {
        "name": Item.FERTILIZER,
        "price": 1750,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [2],
      },
      {
        "name": Item.ETHANOL,
        "price": 480,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [10],
      },
      {
        "name": Item.VINEGAR,
        "price": 500,
        "amount": 500000,
        "unit": Unit.LIQUID,
        "quantity": [10],
      },
      {
        "name": Item.KEYCHAIN,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
      },
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.FLASHLIGHT,
        "price": 4000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.CROWBAR,
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.GLASSES,
        "price": 1100,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.BASEBALL_CAP,
        "price": 300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.BANDAGE,
        "price": 8000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
      },
      {
        "name": Item.MAP,
        "price": 2300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.BUS_TICKET,
        "price": 20,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [25],
      },
      {
        "name": Item.ROLLING_PAPERS,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [40],
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [500],
      },
      {
        "name": Item.DUCT_TAPE,
        "price": 5,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100],
      },
      {
        "name": Item.STRETCH_FOIL,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [80],
      },
      {
        "name": Item.PLASTIC_BAG,
        "price": 250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.CASH_LARGE,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100000],
      },
    ]
  },
  {
    "name": "Construction store",
    "area": Area.SLAVS_BAY,
    "check-possible": false,
    "location": {x: 0.378339, y: 0.594292},
    "discounts": [0.0, 0.1],
    "items": [
      {
        "name": Item.WATER_BOTTLE_MEDIUM,
        "price": 1300,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [1],
      },
      {
        "name": Item.PACKET_SODA,
        "price": 700,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [10],
      },
      {
        "name": Item.ACETONE,
        "price": 3000,
        "amount": 1000,
        "unit": Unit.LIQUID,
        "quantity": [5],
      },
      {
        "name": Item.AMMONIA,
        "price": 1750,
        "amount": 1000,
        "unit": Unit.LIQUID,
        "quantity": [5],
      },
      {
        "name": Item.METHANOL,
        "price": 1150,
        "amount": 300,
        "unit": Unit.LIQUID,
        "quantity": [2],
      },
      {
        "name": Item.FERTILIZER,
        "price": 1750,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [5],
      },
      {
        "name": Item.FERTILIZER_SYNTHETIC,
        "price": 1200,
        "amount": 3000,
        "unit": Unit.MASS,
        "quantity": [3],
      },
      {
        "name": Item.WIRE_CUTTERS,
        "price": 4500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1000],
      },
      {
        "name": Item.DUCT_TAPE,
        "price": 3,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100],
      },
      {
        "name": Item.STRETCH_FOIL,
        "price": 5,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100],
      },
      {
        "name": Item.PLASTIC_BAG,
        "price": 250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
    ]
  },
  {
    "name": "Old lady",
    "area": Area.SLAVS_BAY,
    "check-possible": false,
    "location": {x: 0.432411, y: 0.638772},
    "discounts": [0.0, 0.1, 0.2],
    "items": [
      {
        "name": Item.POPPY_HEAD_YOUNG,
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [6],
      },
      {
        "name": Item.MORNING_GLORY,
        "price": 800,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.ERGOT_RYE,
        "price": 1100,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.YEW_TREE_BRANCH,
        "price": 1300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
    ]
  },
  {
    "name": "Fuel depot",
    "area": Area.SLAVS_BAY,
    "check-possible": true,
    "location": {x: 0.314825, y: 0.548459},
    "discounts": [0.0],
    "items": [
      {
        "name": Item.GASOLINE,
        "price": 6000,
        "amount": 4000,
        "unit": Unit.LIQUID,
        "quantity": [12],
      },
      {
        "name": Item.GASOLINE,
        "price": 16500,
        "amount": 4,
        "unit": Unit.LIQUID,
        "quantity": [4],
      },
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.WIRE_CUTTERS,
        "price": 4500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.CROWBAR,
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.METAL_PARTS,
        "price": 900,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [20],
      },
      {
        "name": Item.ELECTRIC_WIRES,
        "price": 900,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [20],
      },
      {
        "name": Item.MAP,
        "price": 2500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.YACHT_SMALL,
        "price": 470000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.MOTORBOAT,
        "price": 315000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
    ]
  }, // Finished
  {
    "name": "Outdoor weed store",
    "area": Area.SLAVS_BAY,
    "check-possible": false,
    "location": {x: 0.376622, y: 0.576782},
    "discounts": [0.0, 0.1],
    "items": [
      {
        "name": Item.SEED_SATIVA,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5],
      },
      {
        "name": Item.WEED_SATIVA,
        "price": 12000,
        "amount": 10,
        "unit": Unit.MASS,
        "quantity": [1],
      },
      {
        "name": Item.LED_BULB_SMALL,
        "price": 3700,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.UV_BULB_LARGE,
        "price": 9400,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.HYDROPONIC_ELEMENTS,
        "price": 9000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2],
      },
      {
        "name": Item.FLOWER_POT,
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3],
      },
      {
        "name": Item.FAN,
        "price": 2250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
      },
      {
        "name": Item.EMPTY_GLASS_PIPE,
        "price": 5,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10],
      },
      {
        "name": Item.VIAL,
        "price": 2,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [50],
      },
      {
        "name": Item.ROLLING_PAPERS,
        "price": 4,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [40],
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [50],
      },
    ]
  },
  // Peninsular
  {
    "name": "Mini-market",
    "area": Area.PENINSULAR,
    "check-possible": true,
    "location": {x: 0.266246, y: 0.605793},
    "discounts": [0.0, 0.05, 0.1],
    "items": [
      {
        "name": Item.WATER_BOTTLE_SMALL,
        "price": 300,
        "amount": 500,
        "unit": Unit.LIQUID,
        "quantity": [20, 25, 30],
      },
      {
        "name": Item.WATER_BOTTLE_MEDIUM,
        "price": 1300,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [10, 15, 20],
      },
      {
        "name": Item.BEER,
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10, 15, 20],
      },
      {
        "name": Item.CHOCOLATE_BAR,
        "price": 300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 10, 15],
      },
      {
        "name": Item.PACKET_SUGAR,
        "price": 1200,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [20, 25, 30],
      },
      {
        "name": Item.PACKET_FLOUR,
        "price": 550,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [20, 25, 30],
      },
      {
        "name": Item.PACKET_SALT,
        "price": 450,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [20, 25, 30],
      },
      {
        "name": Item.PACKET_SODA,
        "price": 700,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [20, 25, 30],
      },
      {
        "name": Item.CACAO_POWDER,
        "price": 1500,
        "amount": 500,
        "unit": Unit.MASS,
        "quantity": [8, 12, 18],
      },
      {
        "name": Item.POPPY_SEED_PACK,
        "price": 3200,
        "amount": 100,
        "unit": Unit.MASS,
        "quantity": [4, 6, 8],
      },
      {
        "name": Item.ACETONE,
        "price": 3000,
        "amount": 1000,
        "unit": Unit.LIQUID,
        "quantity": [2, 3, 5],
      },
      {
        "name": Item.AMMONIA,
        "price": 1700,
        "amount": 1000,
        "unit": Unit.LIQUID,
        "quantity": [1, 2, 3],
      },
      {
        "name": Item.METHANOL,
        "price": 1150,
        "amount": 300,
        "unit": Unit.LIQUID,
        "quantity": [1, 2, 3],
      },
      {
        "name": Item.ETHANOL,
        "price": 480,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [10, 20, 30],
      },
      {
        "name": Item.VINEGAR,
        "price": 500,
        "amount": 500000,
        "unit": Unit.LIQUID,
        "quantity": [10, 20, 30],
      },
      {
        "name": Item.CIGARETTE_PACK,
        "price": 3750,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10, 15, 20],
      },
      {
        "name": Item.TABACCO_PACK,
        "price": 4500,
        "amount": 50,
        "unit": Unit.MASS,
        "quantity": [5, 10, 20],
      },
      {
        "name": Item.FERTILIZER,
        "price": 1200,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [3, 6, 9],
      },
      {
        "name": Item.FERTILIZER,
        "price": 8750,
        "amount": 5000,
        "unit": Unit.MASS,
        "quantity": [3, 6, 9],
      },
      {
        "name": Item.FERTILIZER_SYNTHETIC,
        "price": 1200,
        "amount": 3000,
        "unit": Unit.MASS,
        "quantity": [3, 5, 9],
      },
      {
        "name": Item.KEYCHAIN,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3, 4, 5],
      },
      {
        "name": Item.COOKING_POT,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3, 4],
      },
      {
        "name": Item.FLASHLIGHT_SMALL,
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 4, 6],
      },
      {
        "name": Item.FLASHLIGHT,
        "price": 4000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 3],
      },
      {
        "name": Item.CROWBAR,
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 2, 3],
      },
      {
        "name": Item.WIRE_CUTTERS,
        "price": 4500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 2, 3],
      },
      {
        "name": Item.MOBILE_PHONE,
        "price": 19000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3, 4],
      },
      {
        "name": Item.MAP,
        "price": 2300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 4, 6],
      },
      {
        "name": Item.GLASSES,
        "price": 1100,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3, 5],
      },
      {
        "name": Item.BASEBALL_CAP,
        "price": 300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 4, 5],
      },
      {
        "name": Item.TSHIRT,
        "price": 450,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 3, 5],
      },
      {
        "name": Item.PANTS,
        "price": 1500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2, 5],
      },
      {
        "name": Item.BACKPACK_SMALL,
        "price": 1800,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3, 5, 7],
      },
      {
        "name": Item.BANDAGE,
        "price": 8000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 10, 15],
      },
      {
        "name": Item.ROLLING_PAPERS,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100, 150, 200],
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1000, 1500, 2000],
      },
      {
        "name": Item.DUCT_TAPE,
        "price": 5,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100, 500, 1000],
      },
      {
        "name": Item.STRETCH_FOIL,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [80, 450, 950],
      },
      {
        "name": Item.PLASTIC_BAG,
        "price": 250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [20, 20, 20],
      },
      {
        "name": Item.BUS_TICKET,
        "price": 20,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100, 100, 100],
      },
      {
        "name": Item.CASH_LARGE,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [100000, 200000, 300000],
      },
    ]
  }, // Finished
  {
    "name": "Pharmacy",
    "area": Area.PENINSULAR,
    "check-possible": false,
    "location": {x: 0.271911, y: 0.607851},
    "discounts": [0.0, 0.1, 0.2],
    "items": [
      {
        "name": Item.BANDAGE,
        "price": 8000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10, 30],
      },
      {
        "name": Item.FIRST_AID_KIT,
        "price": 18000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [3, 8],
      },
      {
        "name": Item.ANTIVENOM,
        "price": 10000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10, 20],
      },
      {
        "name": Item.BOTTLE_COUGH_SYRUP,
        "price": 1500,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [10, 25],
      },
      {
        "name": Item.MIGRAINE_MEDICINE,
        "price": 2200,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [10, 25],
      },
      {
        "name": Item.MEDICARE_PACKAGE,
        "price": 24000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10, 25],
      },
      {
        "name": Item.EPHEDRINE,
        "price": 13500,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [5, 10],
      },
      {
        "name": Item.ETHANOL,
        "price": 480,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [20, 40],
      },
      {
        "name": Item.PHENYL,
        "price": 2900,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [0, 9],
      },
      {
        "name": Item.ACETONE,
        "price": 3000,
        "amount": 1000,
        "unit": Unit.LIQUID,
        "quantity": [0, 5],
      },
      {
        "name": Item.ACETONE,
        "price": 13500,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [0, 1],
      },
      {
        "name": Item.AMMONIA,
        "price": 1750,
        "amount": 1000,
        "unit": Unit.LIQUID,
        "quantity": [0, 6],
      },
      {
        "name": Item.AMMONIA,
        "price": 8750,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [0, 1],
      },
      {
        "name": Item.METHANOL,
        "price": 1150,
        "amount": 300,
        "unit": Unit.LIQUID,
        "quantity": [1, 9],
      },
      {
        "name": Item.METHANOL,
        "price": 17000,
        "amount": 5000,
        "unit": Unit.LIQUID,
        "quantity": [0, 2],
      },
      {
        "name": Item.EMPTY_LABELED_MEDICAL_VIAL,
        "price": 6,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 50],
      },
      {
        "name": Item.EMPTY_LABELED_MEDICAL_BOX,
        "price": 10,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 15],
      },
      {
        "name": Item.PLASTIC_BAG,
        "price": 250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [5, 5],
      },
    ]
  },
  // Sangrienta
  {
    "name": "Ghetto equipment store",
    "area": Area.SANGRIENTA,
    "check-possible": false,
    "location": {x: 0.553256, y: 0.413876},
    "discounts": [0.0, 0.1, 0.15],
    "furnitures": [
      {
        "name": "Small container",
        "price": 300,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 20],
        "substance-storage": 750,
      },
      {
        "name": "Medium container",
        "price": 500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 15],
        "substance-storage": 1500,
      },
      {
        "name": "Large container",
        "price": 900,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 8],
        "substance-storage": 5000,
      },
      {
        "name": "Small barrel",
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [2, 5],
        "substance-storage": 10000,
      },
      {
        "name": "Medium barrel",
        "price": 3500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 3],
        "substance-storage": 20000,
        "visibility": 0.5,
      },
      {
        "name": "Large barrel",
        "price": 7000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1, 2],
        "substance-storage": 50000,
        "visibility": 0.5,
      },
      {
        "name": "Small safe",
        "price": 34000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 10],
      },
      {
        "name": "Safe",
        "price": 240000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 8],
      },
      {
        "name": "Large safe",
        "price": 600000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 2],
      },
      {
        "name": "Window bars",
        "price": 4500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 8],
        "visibility": 0.5,
        "security": 2,
      },
      {
        "name": "Window shutters",
        "price": 4000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 8],
        "visibility": -2,
        "security": 1,
        "blocks-grenades": true,
      },
      {
        "name": "Door lock",
        "price": 6000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 7],
        "security": 7,
      },
      {
        "name": "Large door lock",
        "price": 8500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 4],
        "security": 15,
      },
      {
        "name": "Laboratory cabinet",
        "price": 5000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 4],
        "slots": 8,
        "hideout-stash": 1,
      },
      {
        "name": "Large laboratory cabinet",
        "price": 19000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 3],
        "slots": 40,
        "hideout-stash": 1,
      },
    ],
    "equipments": [
      {
        "name": "Laboratory tray",
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 3],
        "tier": 1,
        "visibility": 0.5,
        "hideout-stash": 1,
        "substance-storage": 150,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Mortar",
        "price": 4000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 4],
        "tier": 1,
        "visibility": 0.5,
        "crafting-speed": 0.4,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Coffe grinder",
        "price": 8000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 3],
        "tier": 2,
        "visibility": 0.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 120,
      },
      {
        "name": "Kitchen stove with oven",
        "price": 22000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 4],
        "visibility": 1,
        "tier": 1,
        "crafting-speed": 0.7,
        "waste-amount": 1.2,
        "production-cost": 1,
        "energy-usage": 2500,
      },
      {
        "name": "Electric pressure cooker",
        "price": 30000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 3],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1.15,
        "waste-amount": 0.95,
        "production-cost": 1,
        "energy-usage": 2000,
      },
      {
        "name": "Laboratory autoclave",
        "price": 65000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 3],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1.3,
        "waste-amount": 0.8,
        "production-cost": 1,
        "energy-usage": 1400,
      },
      {
        "name": "Laboratory water bath",
        "price": 110000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 2],
        "tier": 3,
        "visibility": 1.5,
        "crafting-speed": 1.6,
        "waste-amount": 0.5,
        "production-cost": 1,
        "energy-usage": 2400,
      },
      {
        "name": "Laboratory ice bath",
        "price": 190000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 1],
        "tier": 4,
        "visibility": 2,
        "crafting-speed": 1.7,
        "waste-amount": 0.5,
        "production-cost": 1,
        "energy-usage": 1200,
      },
      {
        "name": "Laboratory centrifuge",
        "price": 140000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 2],
        "tier": 3,
        "visibility": 1,
        "crafting-speed": 1.7,
        "waste-amount": 0.4,
        "production-cost": 1,
        "energy-usage": 150,
      },
      {
        "name": "Laboratory orbital shaker",
        "price": 250000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 1],
        "tier": 4,
        "visibility": 1.5,
        "crafting-speed": 2,
        "waste-amount": 0.2,
        "production-cost": 1,
        "energy-usage": 300,
      },
      {
        "name": "Drying rack",
        "price": 7000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 5],
        "tier": 1,
        "visibility": 1,
        "crafting-speed": 0.8,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Drying outdoor rack",
        "price": 21000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 5],
        "tier": 2,
        "visibility": 3.5,
        "crafting-speed": 1.05,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Hybrid dryer",
        "price": 46000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 4],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1.3,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 50,
      },
      {
        "name": "Laboratory oven",
        "price": 95000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [0, 1],
        "tier": 3,
        "visibility": 1.5,
        "crafting-speed": 1.6,
        "waste-amount": 0.9,
        "production-cost": 1,
        "energy-usage": 2000,
      },
      {
        "name": "Bucket",
        "price": 2000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 3],
        "tier": 1,
        "visibility": 0.5,
        "crafting-speed": 0.5,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Old barrel",
        "price": 4000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 2],
        "tier": 1,
        "visibility": 1.5,
        "crafting-speed": 0.6,
        "waste-amount": 1.1,
        "production-cost": 1,
      },
      {
        "name": "Kitchen mixer",
        "price": 18000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 2],
        "tier": 2,
        "visibility": 1,
        "crafting-speed": 1,
        "waste-amount": 0.8,
        "production-cost": 1,
        "energy-usage": 1500,
      },
      {
        "name": "Small fermentation vat",
        "price": 11000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [1],
        "visibility": 1,
        "tier": 2,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Homemade soaking vat",
        "price": 40000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 3],
        "tier": 2,
        "visibility": 2,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Growbox",
        "price": 32000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 3],
        "tier": 1,
        "visibility": 1.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 80,
      },
      {
        "name": "Rack (for plants)",
        "price": 35500,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 4],
        "tier": 2,
        "visibility": 1.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
        "energy-usage": 150,
      },
      {
        "name": "Seedling box",
        "price": 3000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 5],
        "tier": 2,
        "visibility": 0.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Outdoor pot box",
        "price": 15000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 3],
        "tier": 2,
        "visibility": 2,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },
      {
        "name": "Plastic box (for plants)",
        "price": 4000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 2],
        "tier": 2,
        "visibility": 0.5,
        "crafting-speed": 1,
        "waste-amount": 1,
        "production-cost": 1,
      },

    ],
  },
  {
    "name": "The baker",
    "area": Area.SANGRIENTA,
    "check-possible": false,
    "location": {x: 0.546733, y: 0.371113},
    "discounts": [0.0, 0.1],
    "items": [
      {
        "name": Item.PACKET_FLOUR,
        "price": 550,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [20],
      },
      {
        "name": Item.ERGOT_RYE,
        "price": 1100,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10],
      },
      {
        "name": Item.POPPY_SEED_PACK,
        "price": 31000,
        "amount": 1000,
        "unit": Unit.MASS,
        "quantity": [1],
      },
      {
        "name": Item.POPPY_HEAD_YOUNG,
        "price": 550,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [10],
      },
      {
        "name": Item.OPIUM,
        "price": 13200,
        "amount": 10,
        "unit": Unit.MASS,
        "quantity": [2],
      },
      {
        "name": Item.PLASTIC_BAGGIES,
        "price": 1,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [50],
      },
    ]
  },
  // Volcano Island
  // Dueno del mar
  {
    "name": "Pharmacy",
    "area": Area.DUENO_DEL_MAR,
    "check-possible": false,
    "location": {x: 0.376794, y: 0.402718},
    "discounts": [0.0, 0.1, 0.2],
    "items": [
      {
        "name": Item.BANDAGE,
        "price": 8000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 25, 30],
      },
      {
        "name": Item.FIRST_AID_KIT,
        "price": 18000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 8, 10],
      },
      {
        "name": Item.ANTIVENOM,
        "price": 10000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 8, 40],
      },
      {
        "name": Item.BOTTLE_COUGH_SYRUP,
        "price": 1500,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [-1, 25, 30],
      },
      {
        "name": Item.MIGRAINE_MEDICINE,
        "price": 2200,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [-1, 25, 30],
      },
      {
        "name": Item.EPHEDRINE,
        "price": 13500,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [-1, 3, 4],
      },
      {
        "name": Item.PHENYL,
        "price": 2900,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [-1, 3, 4],
      },
      {
        "name": Item.MEDICARE_PACKAGE,
        "price": 24000,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 15, 30],
      },
      {
        "name": Item.ETHANOL,
        "price": 480,
        "amount": 200,
        "unit": Unit.LIQUID,
        "quantity": [-1, 40, 50],
      },
      {
        "name": Item.METHANOL,
        "price": 1150,
        "amount": 300,
        "unit": Unit.LIQUID,
        "quantity": [-1, 4, 6],
      },
      {
        "name": Item.PLASTIC_BAG,
        "price": 250,
        "amount": 1,
        "unit": Unit.ITEM,
        "quantity": [-1, 5, 5],
      },
    ]
  },
  // Bahia - Downtown
  // Bahia - Favela
]